// templates/web/react-vite/src/pages/Home.tsx
import { useAuth } from "@seamless-auth/react";
import { Link } from "react-router-dom";
import { ActionCard, Screen, StatRow } from "../components/kit";

/*
 * Where a signed-in visitor lands. Composed from the kit, like every other screen.
 */
export default function Home() {
  const { isAuthenticated, loading, user } = useAuth();

  if (loading) {
    return (
      <div className="px-8 py-20 text-sm text-ink-muted">
        Checking your session...
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="px-8 py-20">
        <h1 className="title text-ink">You are signed out</h1>
        <p className="mt-3 max-w-prose text-ink-muted">
          Sign in to see how authentication state flows through the UI and the
          API.
        </p>

        <Link
          to="/login"
          className="lift mt-8 inline-block rounded-control bg-brand px-5 py-2.5 text-sm font-semibold text-brand-ink hover:bg-brand-hover"
        >
          Sign in
        </Link>
      </div>
    );
  }

  const identity = user?.email || user?.phone || user?.id || "your account";

  return (
    <Screen
      archetype="dashboard"
      title="You are signed in"
      tagline={`Signed in as ${identity}.`}
      band={
        <StatRow
          onBand
          items={[
            { label: "Roles", value: user?.roles.length ?? 0 },
            {
              label: "Account",
              value: user?.roles.length
                ? user.roles.join(", ")
                : "No roles yet",
            },
          ]}
        />
      }
    >
      <div className="stagger grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <ActionCard
          to="/session"
          title="Inspect this session"
          body="What the auth server knows about you right now."
        />
        <ActionCard
          to="/beta"
          title="A protected route"
          body="A page and an API call that both require a role."
        />
        <ActionCard
          to="/about"
          title="How this works"
          body="The pieces of Seamless Auth and how they fit together."
        />
      </div>
    </Screen>
  );
}

// templates/web/angular/src/app/pages/home.ts
import { Component, computed, inject } from "@angular/core";
import { RouterLink } from "@angular/router";
import { SeamlessAuth } from "@seamless-auth/angular";

@Component({
  selector: "app-home",
  imports: [RouterLink],
  template: `
    <section class="space-y-10">
      <header class="space-y-2">
        <h1 class="font-display text-4xl tracking-display text-ink">
          You are signed in
        </h1>
        <p class="text-ink-muted">Signed in as {{ identity() }}.</p>
      </header>

      <dl class="grid gap-4 sm:grid-cols-2">
        <div class="rounded-card border border-line bg-surface-raised p-6">
          <dt class="label text-ink-muted">Roles</dt>
          <dd class="mt-2 text-2xl font-semibold text-ink">
            {{ roles().length }}
          </dd>
        </div>
        <div class="rounded-card border border-line bg-surface-raised p-6">
          <dt class="label text-ink-muted">Account</dt>
          <dd class="mt-2 text-sm font-medium text-ink">
            {{ roles().length ? roles().join(", ") : "No roles yet" }}
          </dd>
        </div>
      </dl>

      <div class="grid gap-4 sm:grid-cols-2">
        <a
          routerLink="/beta"
          class="rounded-card border border-line bg-surface-raised p-6 hover:border-accent"
        >
          <h2 class="font-semibold text-ink">A protected route</h2>
          <p class="mt-1 text-sm text-ink-muted">
            A page and an API call that both require a role.
          </p>
        </a>
        <a
          routerLink="/about"
          class="rounded-card border border-line bg-surface-raised p-6 hover:border-accent"
        >
          <h2 class="font-semibold text-ink">How this works</h2>
          <p class="mt-1 text-sm text-ink-muted">
            The pieces of Seamless Auth and how they fit together.
          </p>
        </a>
      </div>
    </section>
  `,
})
export class Home {
  private readonly auth = inject(SeamlessAuth);

  protected readonly identity = computed(() => {
    const user = this.auth.user();
    return user?.email || user?.phone || user?.id || "your account";
  });
  protected readonly roles = computed(() => this.auth.user()?.roles ?? []);
}
